version: "3"

silent: true

vars:
  TYPST_FILENAME: src/main.typ
  PDF_FILENAME: build/sukeshResume.pdf

tasks:
  default:
    desc: Compile the resume in "dev mode".
    summary: |
      Compile the resume in "dev mode".

      This command is expected to be ONLY run in dev mode as it watches for changes and
      recompiles the Typst file as needed. The command is not optimised for production
      usage and hence should not be treated as such.
    cmd: typst watch {{ .TYPST_FILENAME }} {{ .PDF_FILENAME }}

  build:
    desc: Compile the Typst file to PDF
    summary: |
      Compile the Typst file to PDF.

      This command will invoke the "typst" command to compile the "resume.typ" file in to
      a PDF file which can then be accessed through a PDF viewer.
    sources:
      - "{{ .TYPST_FILENAME }}"
    generates:
      - "{{.PDF_FILENAME}}"
    status:
      - test -x "$(command -v typst)"
    cmds:
      - "[[ -d build ]] || mkdir build"
      - echo "Compiling the {{ .TYPST_FILENAME }} file to {{ .PDF_FILENAME }}"
      - typst compile {{ .TYPST_FILENAME }} {{ .PDF_FILENAME }}

  cleanup:
    desc: Cleanup the repository of any unncessary artifacts.
    summary: |
      Clean up any artifacts (including the generated PDF file).

      Invoking this command will remove any unnecessary artifacts including the generated
      PDF file. Run this task when you need to regenerate the PDF file from scratch for
      whatever reason it may be.
    cmds:
      - echo "Cleaning up artifacts"
      - rm --recursive --force {{ .PDF_FILENAME }}
